--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/zSALLAZAR/FFA
build-by-default: true
branches:
- main
projects:
  FFA:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.1.0
      - src: poggit/libasynql/libasynql
        version: ^4.2.3
    lint:
      phpstan: false
...
