--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/zSALLAZAR/FFA
build-by-default: true
branches:
- main
projects:
  FFA:
    path: ""
    libs:
      - src: Frago9876543210/forms/libforms
        version: ^1.0.0
    lint:
      phpstan: false
...
