# Do not change this
config-version: 1.0

database:
    # The database type. "sqlite" and "mysql" are supported.
    type: sqlite

    # Edit these settings only if you choose "sqlite".
    sqlite:
        # The file name of the database in the plugin data folder.
        # You can also put an absolute path here.
        file: data.sqlite
    # Edit these settings only if you choose "mysql".
    mysql:
        host: 127.0.0.1
        # Avoid using the "root" user for security reasons.
        username: root
        password: ""
        schema: your_schema
    # The maximum number of simultaneous SQL queries
    # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
    worker-limit: 1

settings:
    prefix: "§l§gFFA §7»§r "

    # If the scoreboard should be enabled
    scoreboard: true

    # How long it takes for players to be out of combat after being hit in seconds
    # Set this to 0 if you want to disable this
    combat-time: 10

    # The item that opens the ffa forms
    form-item: "nether_star"

    # The center of the safe-zone will be the spawn-position
    safe-zone:
        center: 0;50;0
        radius: 10