# Do not change this
config-version: 1.0

settings:
    prefix: "§l§gFFA §7»§r "

    # If the scoreboard should be enabled
    scoreboard: true

    # How long it takes for players to be out of combat after being hit in seconds
    # Set this to 0 if you want to disable this
    combat-time: 10

    # The center of the safe-zone will be the spawn-position
    safe-zone:
        center: 0;50;0
        radius: 10